/*
 * Code generated from Atmel Start.
 *
 * This file will be overwritten when reconfiguring your Atmel Start project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */
#ifndef ATMEL_START_PINS_H_INCLUDED
#define ATMEL_START_PINS_H_INCLUDED

#include <hal_gpio.h>

#define PA08 GPIO(GPIO_PORTA, 8)
#define PA09 GPIO(GPIO_PORTA, 9)
#define PA10 GPIO(GPIO_PORTA, 10)
#define PA11 GPIO(GPIO_PORTA, 11)
#define PA12 GPIO(GPIO_PORTA, 12)
#define PA13 GPIO(GPIO_PORTA, 13)

#define PA22 GPIO(GPIO_PORTA, 22)
#define PA23 GPIO(GPIO_PORTA, 23)

#define PA04 GPIO(GPIO_PORTA, 4)
#define PA05 GPIO(GPIO_PORTA, 5)

#define PA16 GPIO(GPIO_PORTA, 16)
#define PA17 GPIO(GPIO_PORTA, 17)

#define PA20 GPIO(GPIO_PORTA, 20)
#define PA22 GPIO(GPIO_PORTA, 22)
#define PA23 GPIO(GPIO_PORTA, 23)
#define PA24 GPIO(GPIO_PORTA, 24)
#define PA25 GPIO(GPIO_PORTA, 25)

#define PB04 GPIO(GPIO_PORTB, 4)
#define PB06 GPIO(GPIO_PORTB, 6)

#define PB08 GPIO(GPIO_PORTB, 8)
#define PB09 GPIO(GPIO_PORTB, 9)

#define PB12 GPIO(GPIO_PORTB, 12)
#define PB13 GPIO(GPIO_PORTB, 13)
#define PB15 GPIO(GPIO_PORTB, 15)


#define HW_ID0 GPIO(GPIO_PORTB, 22)
#define HW_ID1 GPIO(GPIO_PORTB, 23)
#define HW_ID2 GPIO(GPIO_PORTB, 30)
#define HW_ID3 GPIO(GPIO_PORTB, 31)
#define DEV_ID0 GPIO(GPIO_PORTB, 12)
#define DEV_ID1 GPIO(GPIO_PORTB, 14)
#define DEV_ID2 GPIO(GPIO_PORTB, 15)
//#define DEV_ID3 GPIO(GPIO_PORTB, 11)

#define EXT GPIO(GPIO_PORTB, 11)			// Extern input

/*#define EXT_TXD GPIO(GPIO_PORTA, 12)
#define EXT_RXD GPIO(GPIO_PORTA, 13)

#define EXT_RW_PIN				15
#define EXT_RW_PORT				GPIO_PORTA
#define EXT_RW GPIO(EXT_RW_PORT, EXT_RW_PIN)
*/
#define PLC_RST GPIO(GPIO_PORTA, 27)
#define PLC_HDC GPIO(GPIO_PORTA, 20)
//#define PLC_RTR GPIO(GPIO_PORTA, 19)
#define PLC_TXON GPIO(GPIO_PORTA, 18)

#define ADC_TINT2 GPIO(GPIO_PORTA, 8)
#define ADC_TINT2_AD PINMUX_PA08B_ADC1_AIN2
#define ADC_TINT2_INPUTCTRL_MUXPOS	ADC_INPUTCTRL_MUXPOS_AIN2
#define ADC_TINT1 GPIO(GPIO_PORTA, 9)
#define ADC_TINT1_AD PINMUX_PA09B_ADC1_AIN3
#define ADC_TINT1_INPUTCTRL_MUXPOS	ADC_INPUTCTRL_MUXPOS_AIN3
#define ADC_VIN GPIO(GPIO_PORTA, 10)
#define ADC_VIN_AD PINMUX_PA10B_ADC0_AIN10
#define ADC_VIN_INPUTCTRL_MUXPOS	ADC_INPUTCTRL_MUXPOS_AIN10

#define ADC_CH1 GPIO(GPIO_PORTB, 8)
#define ADC_CH1_AD PINMUX_PB08B_ADC1_AIN0
#define ADC_CH1_INPUTCTRL_MUXPOS	ADC_INPUTCTRL_MUXPOS_AIN0
#define ADC_CH2 GPIO(GPIO_PORTB, 6)
#define ADC_CH2_AD PINMUX_PB06B_ADC1_AIN8
#define ADC_CH2_INPUTCTRL_MUXPOS	ADC_INPUTCTRL_MUXPOS_AIN8
#define ADC_CH3 GPIO(GPIO_PORTB, 4)
#define ADC_CH3_AD PINMUX_PB04B_ADC1_AIN6
#define ADC_CH3_INPUTCTRL_MUXPOS	ADC_INPUTCTRL_MUXPOS_AIN6
#define ADC_CH4 GPIO(GPIO_PORTB, 5)
#define ADC_CH4_AD PINMUX_PB05B_ADC1_AIN7
#define ADC_CH4_INPUTCTRL_MUXPOS	ADC_INPUTCTRL_MUXPOS_AIN7

#define AD_GND_REF GPIO(GPIO_PORTB, 9)
#define AD_GND_REF_AD PINMUX_PB09B_ADC1_AIN1
#define AD_GND_REF_INPUTCTRL_MUXPOS	ADC_INPUTCTRL_MUXPOS_AIN1
#define AD2_GND_REF GPIO(GPIO_PORTB, 9)
#define AD2_GND_REF_AD PINMUX_PB09B_ADC0_AIN3
#define AD2_GND_REF_INPUTCTRL_MUXPOS	ADC_INPUTCTRL_MUXPOS_AIN3

#define LED_R GPIO(GPIO_PORTB, 1)
#define LED_G GPIO(GPIO_PORTB, 2)
#define LED_B GPIO(GPIO_PORTB, 0)

#define SWITCH GPIO(GPIO_PORTB, 10)
#define PLC_CSEL1 GPIO(GPIO_PORTB, 17)
#define PLC_CSEL0 GPIO(GPIO_PORTB, 16)

#define PB24 GPIO(GPIO_PORTB, 24)
#define PB25 GPIO(GPIO_PORTB, 25)

#define AC_EXT_IN1					GPIO(GPIO_PORTA, 6)			// Schema says TRG1
#define AC_EXT_IN1_FUNC				PINMUX_PB06A_EIC_EXTINT6
#define AC_EXT_IN1_EVENT_BIT		6
#define AC_EXT_IN1_EVENT_SENSE		EIC_CONFIG_SENSE6_FALL
#define AC_EXT_IN1_EVENT_CFG		0							// Config register 8 and above is reg 1
#define AC_EXT_IN1_EVENT_ID_GEN		EVSYS_ID_GEN_EIC_EXTINT_6

#define AC_EXT_IN2					GPIO(GPIO_PORTA, 11)		// Schema says TRG2
#define AC_EXT_IN2_FUNC				PINMUX_PB11A_EIC_EXTINT11
#define AC_EXT_IN2_EVENT_BIT		11
#define AC_EXT_IN2_EVENT_SENSE		EIC_CONFIG_SENSE3_FALL
#define AC_EXT_IN2_EVENT_CFG		1							// Config register 8 and above is reg 1
#define AC_EXT_IN2_EVENT_ID_GEN		EVSYS_ID_GEN_EIC_EXTINT_11

#define AC_EXT_IN3					GPIO(GPIO_PORTA, 4)			// Schema says TRG3
#define AC_EXT_IN3_FUNC				PINMUX_PB04A_EIC_EXTINT4
#define AC_EXT_IN3_EVENT_BIT		4
#define AC_EXT_IN3_EVENT_SENSE		EIC_CONFIG_SENSE4_FALL
#define AC_EXT_IN3_EVENT_CFG		0							// Config register 8 and above is reg 1
#define AC_EXT_IN3_EVENT_ID_GEN		EVSYS_ID_GEN_EIC_EXTINT_4

#define AC_EXT_IN4					GPIO(GPIO_PORTA, 0)			// Schema says TRG4
#define AC_EXT_IN4_FUNC				PINMUX_PA00A_EIC_EXTINT0
#define AC_EXT_IN4_EVENT_BIT		0
#define AC_EXT_IN4_EVENT_SENSE		EIC_CONFIG_SENSE0_FALL
#define AC_EXT_IN4_EVENT_CFG		0							// Config register 8 and above is reg 1
#define AC_EXT_IN4_EVENT_ID_GEN		EVSYS_ID_GEN_EIC_EXTINT_0

#define SW1_PORT					GPIO_PORTA				
#define SW1_PIN						7
#define SW1							GPIO(SW1_PORT, SW1_PIN)

#define SW2_PORT					GPIO_PORTA				// Check Port to event system PORT_EVCTRL_PORTEI0 when changed
#define SW2_PIN						3
#define SW2							GPIO(SW2_PORT, SW2_PIN)

#define SW3_PORT					GPIO_PORTA				// Check Port to event system PORT_EVCTRL_PORTEI0 when changed
#define SW3_PIN						25
#define SW3							GPIO(SW3_PORT, SW3_PIN)

#define SW4_PORT					GPIO_PORTA				// Check Port to event system PORT_EVCTRL_PORTEI0 when changed
#define SW4_PIN						1
#define SW4							GPIO(SW4_PORT, SW4_PIN)

#define DIM1_PORT					GPIO_PORTB
#define DIM1_PIN					13
#define DIM1						GPIO(DIM1_PORT, DIM1_PIN)
#define DIM1_FUNC					PINMUX_PB13F_TCC3_WO1
#define DIM1_WO						1						// & 0x03??	check TCCX_IRQ_MCMP_EN_CH1 + TCCX_INTC_HANDLER_EN_CH1 + TCCX_INTC_INTENSET_CH1 when changed!!

#define DIM2_PORT					GPIO_PORTA
#define DIM2_PIN					19
#define DIM2						GPIO(DIM2_PORT, DIM2_PIN)
#define DIM2_FUNC					PINMUX_PA19F_TCC1_WO3
#define DIM2_WO						3						// & 0x03??	check TCCX_IRQ_MCMP_EN_CH2 + TCCX_INTC_HANDLER_EN_CH2 + TCCX_INTC_INTENSET_CH2 when changed!!

#define DIM3_PORT					GPIO_PORTA
#define DIM3_PIN					24
#define DIM3						GPIO(DIM3_PORT, DIM3_PIN)
#define DIM3_FUNC					PINMUX_PA24F_TCC2_WO2
#define DIM3_WO						2						// & 0x03??	check TCCX_IRQ_MCMP_EN_CH3 + TCCX_INTC_HANDLER_EN_CH3 + TCCX_INTC_INTENSET_CH3 when changed!!

#define DIM4_PORT					GPIO_PORTA
#define DIM4_PIN					21
#define DIM4						GPIO(DIM4_PORT, DIM4_PIN)
#define DIM4_FUNC					PINMUX_PA21G_TCC0_WO1
#define DIM4_WO						1						// & 0x03??	check TCCX_IRQ_MCMP_EN_CH4 + TCCX_INTC_HANDLER_EN_CH4 + TCCX_INTC_INTENSET_CH4 when changed!!

#define LDAC_PORT					GPIO_PORTA				// LDAC port of MCP4728
#define LDAC_PIN					2
#define LDAC						GPIO(LDAC_PORT, LDAC_PIN)

#define RDY_PORT					GPIO_PORTA				// RDY port of MCP4728
#define RDY_PIN						5
#define RDY							GPIO(RDY_PORT, RDY_PIN)

#define SDA_PORT					GPIO_PORTA
#define SDA_PIN						22
#define SDA							GPIO(SDA_PORT, SDA_PIN)
#define SDA_FUNC					PINMUX_PA22C_SERCOM3_PAD0

#define SCL_PORT					GPIO_PORTA
#define SCL_PIN						23
#define SCL							GPIO(SCL_PORT, SCL_PIN)
#define SCL_FUNC					PINMUX_PA23C_SERCOM3_PAD1

/*#define SCIO_PORT					GPIO_PORTB
#define SCIO_PIN					10
#define SCIO						GPIO(SCIO_PORT, SCIO_PIN)
*/
#define EXT_NTC_PORT				GPIO_PORTB
#define EXT_NTC_PIN					3
#define EXT_NTC						GPIO(EXT_NTC_PORT, EXT_NTC_PIN)
#define EXT_NTC_AD					PINMUX_PB03B_ADC0_AIN15
#define EXT_NTC_INPUTCTRL_MUXPOS	ADC_INPUTCTRL_MUXPOS_AIN15

#define EXT_NTC2_PORT				GPIO_PORTB
#define EXT_NTC2_PIN				7
#define EXT_NTC2					GPIO(EXT_NTC_PORT, EXT_NTC_PIN)
#define EXT_NTC2_AD					PINMUX_PB07B_ADC1_AIN9
#define EXT_NTC2_INPUTCTRL_MUXPOS	ADC_INPUTCTRL_MUXPOS_AIN9


#endif // ATMEL_START_PINS_H_INCLUDED
